### ISSUE TITLE
Rails 4.1 support: "creator" method name conflict

### ISSUE THREAD

**Issue by alex-kovshovik** [delynn/userstamp#24]
This is ugly, but "creator" association should probably be renamed to support Rails 4.1 and up.

I'm getting the following error right after Rails 4.1 upgrade:

```
/Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activerecord-4.1.0/lib/active_record/associations/builder/association.rb:30:in `build': You tried to define an association named creator on the model User, but this will conflict with a method creator already defined by Active Record. Please choose a different association name. (ArgumentError)
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activerecord-4.1.0/lib/active_record/associations.rb:1421:in `belongs_to'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/bundler/gems/userstamp-777633aa564f/lib/userstamp/stampable.rb:82:in `block in stampable'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/bundler/gems/userstamp-777633aa564f/lib/userstamp/stampable.rb:81:in `class_eval'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/bundler/gems/userstamp-777633aa564f/lib/userstamp/stampable.rb:81:in `stampable'
    from /Users/alexk/dev/alkaline-morning/app/models/user.rb:8:in `<class:User>'
    from /Users/alexk/dev/alkaline-morning/app/models/user.rb:1:in `<top (required)>'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:443:in `load'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:443:in `block in load_file'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:633:in `new_constants_in'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:442:in `load_file'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:342:in `require_or_load'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:480:in `load_missing_constant'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:180:in `const_missing'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/inflector/methods.rb:238:in `const_get'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/inflector/methods.rb:238:in `block in constantize'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/inflector/methods.rb:236:in `each'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/inflector/methods.rb:236:in `inject'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/inflector/methods.rb:236:in `constantize'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:552:in `get'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:583:in `constantize'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/devise-3.2.4/lib/devise.rb:297:in `get'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/devise-3.2.4/lib/devise/mapping.rb:77:in `to'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/devise-3.2.4/lib/devise/mapping.rb:72:in `modules'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/devise-3.2.4/lib/devise/mapping.rb:89:in `routes'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/devise-3.2.4/lib/devise/mapping.rb:156:in `default_used_route'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/devise-3.2.4/lib/devise/mapping.rb:66:in `initialize'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/devise-3.2.4/lib/devise.rb:331:in `new'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/devise-3.2.4/lib/devise.rb:331:in `add_mapping'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/devise-3.2.4/lib/devise/rails/routes.rb:221:in `block in devise_for'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/devise-3.2.4/lib/devise/rails/routes.rb:220:in `each'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/devise-3.2.4/lib/devise/rails/routes.rb:220:in `devise_for'
    from /Users/alexk/dev/alkaline-morning/config/routes.rb:2:in `block in <top (required)>'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/actionpack-4.1.0/lib/action_dispatch/routing/route_set.rb:335:in `instance_exec'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/actionpack-4.1.0/lib/action_dispatch/routing/route_set.rb:335:in `eval_block'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/actionpack-4.1.0/lib/action_dispatch/routing/route_set.rb:313:in `draw'
    from /Users/alexk/dev/alkaline-morning/config/routes.rb:1:in `<top (required)>'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:241:in `load'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:241:in `block in load'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:232:in `load_dependency'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:241:in `load'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/application/routes_reloader.rb:40:in `each'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/application/routes_reloader.rb:40:in `load_paths'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/application/routes_reloader.rb:16:in `reload!'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/application/routes_reloader.rb:26:in `block in updater'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/file_update_checker.rb:75:in `call'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/file_update_checker.rb:75:in `execute'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/application/routes_reloader.rb:27:in `updater'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/application/finisher.rb:71:in `block in <module:Finisher>'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/initializable.rb:30:in `run'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /Users/alexk/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
    from /Users/alexk/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
    from /Users/alexk/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
    from /Users/alexk/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
    from /Users/alexk/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each'
    from /Users/alexk/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `call'
    from /Users/alexk/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
    from /Users/alexk/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
    from /Users/alexk/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/application.rb:288:in `initialize!'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/railtie.rb:194:in `public_send'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/railtie.rb:194:in `method_missing'
    from /Users/alexk/dev/alkaline-morning/config/environment.rb:5:in `<top (required)>'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `require'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `block in require'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:232:in `load_dependency'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `require'
    from /Users/alexk/dev/alkaline-morning/config.ru:3:in `block in <main>'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
    from /Users/alexk/dev/alkaline-morning/config.ru:in `new'
    from /Users/alexk/dev/alkaline-morning/config.ru:in `<main>'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/commands/server.rb:50:in `app'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/commands/server.rb:130:in `log_to_stdout'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/commands/server.rb:67:in `start'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:81:in `block in server'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:76:in `tap'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:76:in `server'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
    from /Users/alexk/.rvm/gems/ruby-2.1.2@am/gems/railties-4.1.0/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

This would require a major version bump and a ton of pain for everybody who uses it. :(

**Comment by JackWells** [comment]
I did not manually create the associations - just used "stampable".  This seems to have the same effect.  So I suppose I need to go through all my models and remove 'stampable', which was put there per previous instructions?
